spring:
  profile: test

blindata:
  url: http://localhost:3000
  user: ""
  password: ""
  tenantUUID: ""
  roleUuid: ""

odm:
  productPlane:
    registryService:
      active: true
      address: http://localhost:8001
    policyService:
      active: false
      address: http://localhost:8005
    notificationService:
      active: false
      address: http://localhost:8006