spring:
  profile: dev

blindata:
  url: http://localhost:3000
  user: ""
  password: ""
  tenantUUID: ""
  roleUuid: ""
  validator:
    active: true
#############################
# ODM projects configurations
#############################
odm:
  productPlane:
    registryService:
      active: true
      address: http://localhost:8001
    policyService:
      active: true
      address: http://localhost:8005
    notificationService:
      active: true
      address: http://localhost:8006

