spring:
  profile: docker

server:
  port: ${SPRING_PORT}
  baseUrl: ${SPRING_BASE_URL}:${SPRING_PORT}


blindata:
  url: ${BLINDATA_URL}
  user: ${BLINDATA_USER}
  password: ${BLINDATA_PWD}
  tenantUUID: ${BLINDATA_TENANT}
  roleUuid: ${BLINDATA_ROLE}

odm:
  productPlane:
    registryService:
      active: ${REGISTRY_ACTIVE}
      address: ${REGISTRY_BASE_URL}:${REGISTRY_PORT}
    policyService:
      active: ${POLICY_ACTIVE}
      address: ${POLICY_BASE_URL}:${POLICY_PORT}
    notificationService:
      active: ${NOTIFICATION_ACTIVE}
      address: ${NOTIFICATION_BASE_URL}:${NOTIFICATION_PORT}