app:
  workdir:

server:
  port: 9002
  baseUrl: http://localhost:9002
  error:
    include-message: always
  servlet:
    context-path: /api/v1/up/

blindata:
  systemNameRegex: ".*"
  systemTechnologyRegex: "[^:]*"
  dependsOnSystemNameRegex: "blindata:systems:(.+)"
  validator:
    active: false
    policyEngine:
      name: blindata_observer_validator
    policy:
      name: blindata_observer_validator_policy
      blocking: true
  eventHandlers:
    - eventType: DATA_PRODUCT_CREATED
      filter: ""
      activeUseCases:
        - DATA_PRODUCT_UPLOAD
    - eventType: DATA_PRODUCT_VERSION_CREATED
      filter: ""
      activeUseCases:
        - DATA_PRODUCT_UPLOAD
        - DATA_PRODUCT_VERSION_UPLOAD
        - STAGES_UPLOAD
        - POLICIES_UPLOAD
    - eventType: DATA_PRODUCT_ACTIVITY_COMPLETED
      filter: ""
      activeUseCases:
        - STAGES_UPLOAD
        - POLICIES_UPLOAD

