package org.opendatamesh.platform.up.metaservice.blindata.services.usecases.marketplace_portupdater;

import org.opendatamesh.platform.up.metaservice.blindata.resources.blindata.marketplace.BDMarketplaceAccessRequestsUploadRes;
import org.opendatamesh.platform.up.metaservice.blindata.resources.blindata.product.BDMarketplaceAccessRequestPortStatusUploadResultsRes;

interface MarketplaceAccessRequestsPortUpdaterBlindataOutboundPort {
    BDMarketplaceAccessRequestPortStatusUploadResultsRes uploadPortStatuses(BDMarketplaceAccessRequestsUploadRes bdMarketplaceAccessRequestsUploadRes);
}
