CREATE SCHEMA IF NOT EXISTS "PUBLIC";

CREATE TABLE "PUBLIC"."NOTIFICATION"(
    "SEQUENCE_ID" SERIAL PRIMARY KEY,
    "STATUS" VARCHAR(255),
    "PROCESSING_OUTPUT" VARCHAR(255),
    "EVENT_ID" BIGINT,
    "NOTIFICATION_ID" BIGINT REFERENCES NOTIFICATION(SEQUENCE_ID),
    "EVENT_TYPE" VARCHAR(255),
    "EVENT_ENTITY_ID" VARCHAR(255),
    "EVENT_BEFORE_STATE" TEXT,
    "EVENT_AFTER_STATE" TEXT,
    "EVENT_TIME" TIMESTAMP,
    "RECEIVED_AT" TIMESTAMP,
    "PROCESSED_AT" TIMESTAMP
);
