FROM openjdk:17-alpine

VOLUME /tmp

COPY observer-blindata-server/target/odm-platform-adapter-observer-blindata-server-*.jar ./application.jar

ARG SPRING_PROFILES_ACTIVE=docker
ARG SPRING_PORT=9002
ARG SPRING_BASE_URL=http://localhost
ARG JAVA_OPTS
ARG BLINDATA_URL
ARG BLINDATA_USER
ARG BLINDATA_PWD
ARG BLINDATA_TENANT
ARG BLINDATA_ROLE
ARG REGISTRY_BASE_URL=http://localhost
ARG REGISTRY_PORT=8001
ARG REGISTRY_ACTIVE=true
ARG POLICY_BASE_URL=localhost
ARG POLICY_PORT=8005
ARG POLICY_ACTIVE=true
ARG NOTIFICATION_BASE_URL=http://localhost
ARG NOTIFICATION_PORT=8006
ARG NOTIFICATION_ACTIVE=true

ENV SPRING_PROFILES_ACTIVE ${SPRING_PROFILES_ACTIVE}
ENV SPRING_BASE_URL ${SPRING_BASE_URL}
ENV SPRING_PORT ${SPRING_PORT}
ENV JAVA_OPTS ${JAVA_OPTS}
ENV BLINDATA_URL ${BLINDATA_URL}
ENV BLINDATA_USER ${BLINDATA_USER}
ENV BLINDATA_PWD ${BLINDATA_PWD}
ENV BLINDATA_TENANT ${BLINDATA_TENANT}
ENV BLINDATA_ROLE ${BLINDATA_ROLE}
ENV REGISTRY_ACTIVE ${REGISTRY_ACTIVE}
ENV REGISTRY_BASE_URL ${REGISTRY_BASE_URL}
ENV REGISTRY_PORT ${REGISTRY_PORT}
ENV POLICY_ACTIVE ${POLICY_ACTIVE}
ENV POLICY_BASE_URL ${POLICY_BASE_URL}
ENV POLICY_PORT ${POLICY_PORT}
ENV NOTIFICATION_ACTIVE ${NOTIFICATION_ACTIVE}
ENV NOTIFICATION_BASE_URL ${NOTIFICATION_BASE_URL}
ENV NOTIFICATION_PORT ${NOTIFICATION_PORT}

EXPOSE $SPRING_PORT

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS  -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE $SPRING_PROPS -jar ./application.jar" ]