FROM openjdk:17-alpine

VOLUME /tmp

COPY meta-service-blindata/target/odm-platform-up-meta-service-blindata-*.jar ./application.jar

ARG SPRING_PROFILES_ACTIVE=docker
ARG SPRING_PORT=9002
ARG JAVA_OPTS
ARG DATABASE_URL
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_SCHEMA=ODMNOTIFICATION
ARG FLYWAY_SCRIPTS_DIR=postgresql
ARG H2_CONSOLE_ENABLED=false
ARG H2_CONSOLE_PATH=h2-console
ARG BLINDATA_URL
ARG BLINDATA_USER
ARG BLINDATA_PWD
ARG BLINDATA_TENANT
ARG BLINDATA_ROLE

ENV SPRING_PROFILES_ACTIVE ${SPRING_PROFILES_ACTIVE}
ENV SPRING_PORT ${SPRING_PORT}
ENV JAVA_OPTS ${JAVA_OPTS}
ENV DATABASE_URL ${DATABASE_URL}
ENV DATABASE_USERNAME ${DATABASE_USERNAME}
ENV DATABASE_PASSWORD ${DATABASE_PASSWORD}
ENV DATABASE_SCHEMA ${DATABASE_SCHEMA}
ENV FLYWAY_SCRIPTS_DIR ${FLYWAY_SCRIPTS_DIR}
ENV H2_CONSOLE_ENABLED ${H2_CONSOLE_ENABLED}
ENV H2_CONSOLE_PATH ${H2_CONSOLE_PATH}
ENV BLINDATA_URL ${BLINDATA_URL}
ENV BLINDATA_USER ${BLINDATA_USER}
ENV BLINDATA_PWD ${BLINDATA_PWD}
ENV BLINDATA_TENANT ${BLINDATA_TENANT}
ENV BLINDATA_ROLE ${BLINDATA_ROLE}

EXPOSE $SPRING_PORT

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS  -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE $SPRING_PROPS -jar ./application.jar" ]