package org.opendatamesh.platform.up.metaservice.blindata.resources;

public enum PermissionRes {

    OPERATOR,
    NONE,
    DATA_CATEGORIES_EDITOR,
    DATA_CATEGORIES_VIEWER,
    DATA_CATEGORIES_ADMIN,
    SYSTEMS_VIEWER,
    SYSTEMS_EDITOR,
    SYSTEMS_ADMIN,
    PROCESSINGS_VIEWER,
    PROCESSINGS_EDITOR,
    PROCESSINGS_ADMIN,
    TASKS_VIEWER,
    TASKS_EDITOR,
    TASKS_ADMIN,
    DATA_ACTORS_VIEWER,
    DATA_ACTORS_EDITOR,
    DATA_ACTORS_ADMIN,
    DATA_SUBJECTS_VIEWER,
    DATA_SUBJECTS_EDITOR,
    DATA_SUBJECTS_ADMIN,
    CONSENTS_VIEWER,
    CONSENTS_EDITOR,
    CONSENTS_ADMIN,
    CONTRACTS_VIEWER,
    CONTRACTS_EDITOR,
    CONTRACTS_ADMIN,
    USERS_VIEWER,
    USERS_EDITOR,
    USERS_ADMIN,
    PROPOSE,
    APPROVE,
    STEWARDSHIP_VIEWER,
    STEWARDSHIP_EDITOR,
    STEWARDSHIP_ADMIN,

    CLASSIFICATION_VIEWER,
    CLASSIFICATION_EDITOR,
    CLASSIFICATION_ADMIN,

    CAMPAIGNS_VIEWER,
    CAMPAIGNS_EDITOR,
    CAMPAIGNS_ADMIN,

    QUALITY_VIEWER,
    QUALITY_EDITOR,
    QUALITY_ADMIN,

    PROBES_VIEWER,
    PROBES_EDITOR,
    PROBES_ADMIN,

    QUALITY_ASSMNT_VIEWER,
    QUALITY_ASSMNT_EDITOR,
    QUALITY_ASSMNT_ADMIN,

    QUERY_PARSER_VIEWER,
    QUERY_PARSER_EDITOR,
    QUERY_PARSER_ADMIN,

    DATA_PRODUCTS_VIEWER,
    DATA_PRODUCTS_EDITOR,
    DATA_PRODUCTS_ADMIN,

    AGENTS_VIEWER,
    AGENTS_EDITOR,
    AGENTS_ADMIN;
}
