server:
  port: 8595
  error:
    include-message: always
  servlet:
    context-path: /api/v1/up/metaservice/

spring:
  profile: localpostgres
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        globally_quoted_identifiers: true
        default_schema: PUBLIC
  datasource:
    url: jdbc:postgresql://localhost:5432/odmplatformandmetaservicedb #jdbc:postgresql://localhost:49156/postgres
    username: usr #postgres
    password: pwd #my-secret-password
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/odmplatformandmetaservicedb #jdbc:postgresql://localhost:49156/postgres
    user: usr #postgres
    password: pwd #my-secret-password
      #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: flyway_metaservice #public
    locations: classpath:db/migration/postgres
    clean-on-validation-error: true
