##########################
# Server configuration
##########################
app:
  workdir:

server:
  port: 8595
  error:
    include-message: always
  servlet:
    context-path: /api/v1/up/metaservice/

############################################
# Spring configurations
############################################

spring:
  # Profile
  profile: dev
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.H2Dialect
  # DB
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb
    user: sa
    password:
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: PUBLIC
    locations: classpath:db/migrations/h2
    clean-on-validation-error: true