name: odm-platform-adapter-observer-blindata CI
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.5.2
        with:
          ssh-key: ${{secrets.SSH_KEY}}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Clone and build odm-platform
        run: |
          git config user.name "github-workflows-cloner"
          git config user.email "<>"
          git clone https://github.com/opendatamesh-initiative/odm-platform.git
          cd odm-platform
          mvn -B clean install -DskipTests --file pom.xml
          cd ..
      - name: Build with Maven
        run: mvn clean package spring-boot:repackage -DskipTests
      - name: Execute tests with Maven
        run: |
          mvn -B test -Dspring.profiles.active=test -Dtest=OpaClientIT -DfailIfNoTests=false
          mvn -B test -Dspring.profiles.active=test -Dtest=BlindataServiceIT -DfailIfNoTests=false